version: '3'
services:
  gocore-koliba:
    container_name: gocore-koliba
    build:
      context: https://github.com/core-coin/go-core.git
      dockerfile: Dockerfile
      args:
        NETWORK: koliba
        DATADIR: ~/.koliba
        # Expose ports inside the container
        EXPOSEPORTS: 30300 30300/udp
    # Expose ports outside the server
    ports:
      # - "8545:8545/tcp" # HTTP-RPC
      # - "8546:8546/tcp" # WS
      # - "8547:8547/tcp" # GraphQL
      - "30300:30300/tcp"
      - "30300:30300/udp"
    deploy:
      restart_policy:
        condition: always
